# TOMCAT HTTPS CONFIG
server.port=9898
server.ssl.enabled=true
server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=123456
server.ssl.key-alias=mototaksi

# ? Database Configuration
spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/sifarisqrupu
spring.datasource.username=sifarisqrupuuser
spring.datasource.password=YeniGucluSifre_2026!
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false

# HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_batch_fetch_size=50
